-- ============================================
-- 修复 MyBatis-Plus 实体与数据库表结构不一致问题
-- 为所有继承 BaseEntity 的表添加缺失字段
-- ============================================

-- 食材表
ALTER TABLE ingredient
ADD COLUMN IF NOT EXISTS create_time datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
ADD COLUMN IF NOT EXISTS update_time datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
ADD COLUMN IF NOT EXISTS is_deleted tinyint DEFAULT 0 COMMENT '是否删除(0-否 1-是)';

-- 游戏相关表
ALTER TABLE game_riddle
ADD COLUMN IF NOT EXISTS update_time datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
ADD COLUMN IF NOT EXISTS is_deleted tinyint DEFAULT 0 COMMENT '是否删除';

ALTER TABLE game_quiz
ADD COLUMN IF NOT EXISTS create_time datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
ADD COLUMN IF NOT EXISTS update_time datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
ADD COLUMN IF NOT EXISTS is_deleted tinyint DEFAULT 0 COMMENT '是否删除';

ALTER TABLE game_wheel
ADD COLUMN IF NOT EXISTS create_time datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
ADD COLUMN IF NOT EXISTS update_time datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
ADD COLUMN IF NOT EXISTS is_deleted tinyint DEFAULT 0 COMMENT '是否删除';

-- 家庭挑战相关表
ALTER TABLE family_challenge
ADD COLUMN IF NOT EXISTS create_time datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
ADD COLUMN IF NOT EXISTS update_time datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
ADD COLUMN IF NOT EXISTS is_deleted tinyint DEFAULT 0 COMMENT '是否删除';

ALTER TABLE challenge_participant
ADD COLUMN IF NOT EXISTS create_time datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
ADD COLUMN IF NOT EXISTS update_time datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
ADD COLUMN IF NOT EXISTS is_deleted tinyint DEFAULT 0 COMMENT '是否删除';

ALTER TABLE challenge_checkin
ADD COLUMN IF NOT EXISTS create_time datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
ADD COLUMN IF NOT EXISTS update_time datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
ADD COLUMN IF NOT EXISTS is_deleted tinyint DEFAULT 0 COMMENT '是否删除';

-- 优惠券相关表
ALTER TABLE coupon
ADD COLUMN IF NOT EXISTS create_time datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
ADD COLUMN IF NOT EXISTS update_time datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
ADD COLUMN IF NOT EXISTS is_deleted tinyint DEFAULT 0 COMMENT '是否删除';

ALTER TABLE points_coupon
ADD COLUMN IF NOT EXISTS create_time datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
ADD COLUMN IF NOT EXISTS update_time datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
ADD COLUMN IF NOT EXISTS is_deleted tinyint DEFAULT 0 COMMENT '是否删除';

ALTER TABLE points_coupon_record
ADD COLUMN IF NOT EXISTS create_time datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
ADD COLUMN IF NOT EXISTS update_time datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
ADD COLUMN IF NOT EXISTS is_deleted tinyint DEFAULT 0 COMMENT '是否删除';

-- 食谱相关表
ALTER TABLE recipe
ADD COLUMN IF NOT EXISTS create_time datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
ADD COLUMN IF NOT EXISTS update_time datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
ADD COLUMN IF NOT EXISTS is_deleted tinyint DEFAULT 0 COMMENT '是否删除';

-- 购物相关表
ALTER TABLE shopping_list
ADD COLUMN IF NOT EXISTS create_time datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
ADD COLUMN IF NOT EXISTS update_time datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
ADD COLUMN IF NOT EXISTS is_deleted tinyint DEFAULT 0 COMMENT '是否删除';

ALTER TABLE shopping_item
ADD COLUMN IF NOT EXISTS create_time datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
ADD COLUMN IF NOT EXISTS update_time datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
ADD COLUMN IF NOT EXISTS is_deleted tinyint DEFAULT 0 COMMENT '是否删除';

-- 健康相关表
ALTER TABLE health_record
ADD COLUMN IF NOT EXISTS create_time datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
ADD COLUMN IF NOT EXISTS update_time datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
ADD COLUMN IF NOT EXISTS is_deleted tinyint DEFAULT 0 COMMENT '是否删除';

ALTER TABLE health_indicator
ADD COLUMN IF NOT EXISTS create_time datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
ADD COLUMN IF NOT EXISTS update_time datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
ADD COLUMN IF NOT EXISTS is_deleted tinyint DEFAULT 0 COMMENT '是否删除';

ALTER TABLE diet_record
ADD COLUMN IF NOT EXISTS create_time datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
ADD COLUMN IF NOT EXISTS update_time datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
ADD COLUMN IF NOT EXISTS is_deleted tinyint DEFAULT 0 COMMENT '是否删除';

-- 账本相关表
ALTER TABLE ledger_budget
ADD COLUMN IF NOT EXISTS create_time datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
ADD COLUMN IF NOT EXISTS update_time datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
ADD COLUMN IF NOT EXISTS is_deleted tinyint DEFAULT 0 COMMENT '是否删除';

ALTER TABLE ledger_record
ADD COLUMN IF NOT EXISTS create_time datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
ADD COLUMN IF NOT EXISTS update_time datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
ADD COLUMN IF NOT EXISTS is_deleted tinyint DEFAULT 0 COMMENT '是否删除';

-- 价格记录表
ALTER TABLE price_record
ADD COLUMN IF NOT EXISTS create_time datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
ADD COLUMN IF NOT EXISTS update_time datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
ADD COLUMN IF NOT EXISTS is_deleted tinyint DEFAULT 0 COMMENT '是否删除';

ALTER TABLE price_alert
ADD COLUMN IF NOT EXISTS create_time datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
ADD COLUMN IF NOT EXISTS update_time datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
ADD COLUMN IF NOT EXISTS is_deleted tinyint DEFAULT 0 COMMENT '是否删除';

-- 条码产品表
ALTER TABLE barcode_product
ADD COLUMN IF NOT EXISTS create_time datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
ADD COLUMN IF NOT EXISTS update_time datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
ADD COLUMN IF NOT EXISTS is_deleted tinyint DEFAULT 0 COMMENT '是否删除';

-- 扫码记录表
ALTER TABLE scan_record
ADD COLUMN IF NOT EXISTS create_time datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
ADD COLUMN IF NOT EXISTS update_time datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
ADD COLUMN IF NOT EXISTS is_deleted tinyint DEFAULT 0 COMMENT '是否删除';

-- 商店表
ALTER TABLE store
ADD COLUMN IF NOT EXISTS create_time datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
ADD COLUMN IF NOT EXISTS update_time datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
ADD COLUMN IF NOT EXISTS is_deleted tinyint DEFAULT 0 COMMENT '是否删除';

-- 用户积分表
ALTER TABLE user_points
ADD COLUMN IF NOT EXISTS create_time datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
ADD COLUMN IF NOT EXISTS update_time datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
ADD COLUMN IF NOT EXISTS is_deleted tinyint DEFAULT 0 COMMENT '是否删除';

ALTER TABLE points_transaction
ADD COLUMN IF NOT EXISTS create_time datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
ADD COLUMN IF NOT EXISTS update_time datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
ADD COLUMN IF NOT EXISTS is_deleted tinyint DEFAULT 0 COMMENT '是否删除';

-- 体重记录表
ALTER TABLE weight_record
ADD COLUMN IF NOT EXISTS create_time datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
ADD COLUMN IF NOT EXISTS update_time datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
ADD COLUMN IF NOT EXISTS is_deleted tinyint DEFAULT 0 COMMENT '是否删除';

-- 饮水记录表
ALTER TABLE water_record
ADD COLUMN IF NOT EXISTS create_time datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
ADD COLUMN IF NOT EXISTS update_time datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
ADD COLUMN IF NOT EXISTS is_deleted tinyint DEFAULT 0 COMMENT '是否删除';

-- 用户喝水目标表
ALTER TABLE user_water_goal
ADD COLUMN IF NOT EXISTS create_time datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
ADD COLUMN IF NOT EXISTS update_time datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
ADD COLUMN IF NOT EXISTS is_deleted tinyint DEFAULT 0 COMMENT '是否删除';

-- 饮食记录表（如果表名不同请调整）
ALTER TABLE food
ADD COLUMN IF NOT EXISTS create_time datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
ADD COLUMN IF NOT EXISTS update_time datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
ADD COLUMN IF NOT EXISTS is_deleted tinyint DEFAULT 0 COMMENT '是否删除';

-- 库存表
ALTER TABLE inventory
ADD COLUMN IF NOT EXISTS create_time datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
ADD COLUMN IF NOT EXISTS update_time datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
ADD COLUMN IF NOT EXISTS is_deleted tinyint DEFAULT 0 COMMENT '是否删除';

-- 日程表
ALTER TABLE schedule
ADD COLUMN IF NOT EXISTS create_time datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
ADD COLUMN IF NOT EXISTS update_time datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
ADD COLUMN IF NOT EXISTS is_deleted tinyint DEFAULT 0 COMMENT '是否删除';

-- 相册相关表
ALTER TABLE family_album
ADD COLUMN IF NOT EXISTS create_time datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
ADD COLUMN IF NOT EXISTS update_time datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
ADD COLUMN IF NOT EXISTS is_deleted tinyint DEFAULT 0 COMMENT '是否删除';

ALTER TABLE album_photo
ADD COLUMN IF NOT EXISTS create_time datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
ADD COLUMN IF NOT EXISTS update_time datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
ADD COLUMN IF NOT EXISTS is_deleted tinyint DEFAULT 0 COMMENT '是否删除';

-- 时刻（朋友圈）相关表
ALTER TABLE moment
ADD COLUMN IF NOT EXISTS create_time datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
ADD COLUMN IF NOT EXISTS update_time datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
ADD COLUMN IF NOT EXISTS is_deleted tinyint DEFAULT 0 COMMENT '是否删除';

ALTER TABLE moment_comment
ADD COLUMN IF NOT EXISTS create_time datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
ADD COLUMN IF NOT EXISTS update_time datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
ADD COLUMN IF NOT EXISTS is_deleted tinyint DEFAULT 0 COMMENT '是否删除';

-- 报表和统计表
ALTER TABLE family_report
ADD COLUMN IF NOT EXISTS create_time datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
ADD COLUMN IF NOT EXISTS update_time datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
ADD COLUMN IF NOT EXISTS is_deleted tinyint DEFAULT 0 COMMENT '是否删除';

ALTER TABLE stats_cache
ADD COLUMN IF NOT EXISTS create_time datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
ADD COLUMN IF NOT EXISTS update_time datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
ADD COLUMN IF NOT EXISTS is_deleted tinyint DEFAULT 0 COMMENT '是否删除';

-- 操作日志表
ALTER TABLE operation_log
ADD COLUMN IF NOT EXISTS create_time datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
ADD COLUMN IF NOT EXISTS update_time datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
ADD COLUMN IF NOT EXISTS is_deleted tinyint DEFAULT 0 COMMENT '是否删除';

-- 用户活动表
ALTER TABLE user_activity
ADD COLUMN IF NOT EXISTS create_time datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
ADD COLUMN IF NOT EXISTS update_time datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
ADD COLUMN IF NOT EXISTS is_deleted tinyint DEFAULT 0 COMMENT '是否删除';

-- 账本分类表
ALTER TABLE ledger_category
ADD COLUMN IF NOT EXISTS create_time datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
ADD COLUMN IF NOT EXISTS update_time datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
ADD COLUMN IF NOT EXISTS is_deleted tinyint DEFAULT 0 COMMENT '是否删除';

-- 账本分享表
ALTER TABLE ledger_share
ADD COLUMN IF NOT EXISTS create_time datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
ADD COLUMN IF NOT EXISTS update_time datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
ADD COLUMN IF NOT EXISTS is_deleted tinyint DEFAULT 0 COMMENT '是否删除';

-- 家庭账本表
ALTER TABLE family_ledger
ADD COLUMN IF NOT EXISTS create_time datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
ADD COLUMN IF NOT EXISTS update_time datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
ADD COLUMN IF NOT EXISTS is_deleted tinyint DEFAULT 0 COMMENT '是否删除';

-- 照片标签表
ALTER TABLE photo_tag
ADD COLUMN IF NOT EXISTS create_time datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
ADD COLUMN IF NOT EXISTS update_time datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
ADD COLUMN IF NOT EXISTS is_deleted tinyint DEFAULT 0 COMMENT '是否删除';

-- 食谱记录表
ALTER TABLE recipe_record
ADD COLUMN IF NOT EXISTS create_time datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
ADD COLUMN IF NOT EXISTS update_time datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
ADD COLUMN IF NOT EXISTS is_deleted tinyint DEFAULT 0 COMMENT '是否删除';

-- 用户体重表
ALTER TABLE user_weight
ADD COLUMN IF NOT EXISTS create_time datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
ADD COLUMN IF NOT EXISTS update_time datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
ADD COLUMN IF NOT EXISTS is_deleted tinyint DEFAULT 0 COMMENT '是否删除';

-- 心愿里程碑表
ALTER TABLE wish_milestone
ADD COLUMN IF NOT EXISTS create_time datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
ADD COLUMN IF NOT EXISTS update_time datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
ADD COLUMN IF NOT EXISTS is_deleted tinyint DEFAULT 0 COMMENT '是否删除';

-- 相册分享表
ALTER TABLE album_share
ADD COLUMN IF NOT EXISTS create_time datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
ADD COLUMN IF NOT EXISTS update_time datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
ADD COLUMN IF NOT EXISTS is_deleted tinyint DEFAULT 0 COMMENT '是否删除';

-- 价格历史表
ALTER TABLE price_history
ADD COLUMN IF NOT EXISTS create_time datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
ADD COLUMN IF NOT EXISTS update_time datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
ADD COLUMN IF NOT EXISTS is_deleted tinyint DEFAULT 0 COMMENT '是否删除';

-- 时刻点赞表
ALTER TABLE moment_like
ADD COLUMN IF NOT EXISTS create_time datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
ADD COLUMN IF NOT EXISTS update_time datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
ADD COLUMN IF NOT EXISTS is_deleted tinyint DEFAULT 0 COMMENT '是否删除';

